import {load} from 'cheerio';
import {createHash} from 'node:crypto';
import {safeUrl} from '../dist/core.js';

const east='America/New_York';
export const conservatorySources=[
 {id:'bu',name:'Boston University School of Music',url:'https://www.bu.edu/cfa/music/concerts-recitals/music-livestream/',timezone:east},
 {id:'hartt',name:'The Hartt School',url:'https://www.hartford.edu/academics/schools-colleges/hartt/performances/livestream.aspx',timezone:east},
 {id:'ithaca',name:'Ithaca College School of Music, Theatre, and Dance',url:'https://www.ithaca.edu/academics/school-music-theatre-and-dance/live/webcasting-schedule',timezone:east},
 {id:'fsu',name:'Florida State University College of Music',url:'https://wfsu.org/fsumusic/',timezone:east},
 {id:'crane',name:'SUNY Potsdam Crane School of Music',url:'https://www.potsdam.edu/academics/crane-school-music/crane-school-music-live-concert',timezone:east},
 {id:'csulb',name:'Bob Cole Conservatory of Music, CSU Long Beach',url:'https://web.csulb.edu/colleges/cota/music/events/',timezone:'America/Los_Angeles'},
 {id:'frost',name:'University of Miami Frost School of Music',url:'https://events.miami.edu/department/frost_school_of_music/calendar',timezone:east}
];
// Hosted requests receive HTTP 403 from Actions. Parser retained for local/manual review only — do not promote onto scheduled sources until the host allows the collector (low-request streaming calendar is otherwise solid).
export const conservatoryCandidates=[
 {id:'byu',name:'Brigham Young University School of Music',url:'https://musicstreaming.byu.edu/calendar',timezone:'America/Denver'}
];
export const conservatoryHosts=['www.bu.edu','www.hartford.edu','www.ithaca.edu','wfsu.org','www.potsdam.edu','web.csulb.edu','events.miami.edu','musicstreaming.byu.edu','onstage.byu.edu','music.byu.edu'];
const info=Object.fromEntries([...conservatorySources,...conservatoryCandidates].map(s=>[s.id,s]));
const excluded=title=>/cancel(?:led|ed)|postponed|\bjazz\b|big band|\bpop\b|\brock\b|lecture|master\s?class|workshop|fundraiser|Beach Caf[eé]|gala|VIP|memorial ceremony|Veterans Day Memorial/i.test(title);
const restricted=text=>/password|members.only|community members only|login required|private stream|pay.per.view|(?:stream|broadcast).{0,30}(?:ticket required|subscription|paid)/i.test(text);
function official(value,base){const url=safeUrl(new URL(value,base).href);if(!url||new URL(url).origin!==new URL(base).origin)throw new Error('Conservatory event destination changed');return url;}
function publicVideo(value){const url=safeUrl(value);if(!url)return null;const u=new URL(url);if(!['youtube.com','www.youtube.com','www.youtube-nocookie.com'].includes(u.hostname))return null;const id=u.pathname.match(/^\/(?:live|embed)\/([\w-]{11})$/)?.[1]||(u.pathname==='/watch'?u.searchParams.get('v'):null);return /^[\w-]{11}$/.test(id||'')?'https://www.youtube.com/watch?v='+id:null;}

export function createConservatories({clean,zonedTime,clock24,namedDate,DAY}){
 const inWindow=(start,now)=>Date.parse(start)>=+now-2*DAY&&Date.parse(start)<+now+45*DAY;
 const dateTime=(text,zone=east,year)=>zonedTime(namedDate(text.replace(/\s+,/g,','),year)+'T'+clock24(text),zone);
 function weekday(date,text){const day=text.match(/\b(Sun|Mon|Tue|Wed|Thu|Fri|Sat)/i)?.[1];if(!day||new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z')).toLowerCase()!==day.toLowerCase())throw new Error('Published weekday and concert date disagree');}
 function nearbyDate(text,now){const years=[now.getUTCFullYear()-1,now.getUTCFullYear(),now.getUTCFullYear()+1];const matches=years.flatMap(year=>{try{const date=namedDate(text,year);weekday(date,text);return Math.abs(Date.parse(date)-+now)<180*DAY?[date]:[];}catch{return [];}});if(matches.length!==1)throw new Error('Concert year cannot be established from dated weekday schedule');return matches[0];}
 function event(id,title,start,extra={}){const source=info[id];return {id:`${id}-${createHash('sha256').update(title+'|'+start).digest('hex').slice(0,16)}`,title,start,end:null,program:'',event_url:source.url,stream_url:source.url,watch_kind:'venue',evidence_url:source.url,...extra};}
 function parseBu(html){const $=load(html),sections=$('.bu_collapsible_container').filter((i,e)=>/\b(?:Fall|Spring) \d{4} Schedule/.test($(e).find('h3').text()));if(!sections.length)throw new Error('BU term webcast schedule missing');return sections.toArray().flatMap(section=>{const year=+$(section).find('h3').text().match(/\d{4}/)[0];return $(section).find('.bu_collapsible_section p').toArray().flatMap(p=>{const text=clean($(p).text()),date=clean($(p).find('strong').first().text());if(!/(?:am|pm)\b/i.test(date))return [];const title=clean(text.slice(date.length));if(!title||excluded(title)||restricted(text))return [];const day=namedDate(date,year);weekday(day,date);return [event('bu',title,dateTime(date,east,year),{watch_note:'BU’s main livestream player changes for each scheduled concert.',evidence:'Official livestream page lists this performance in its dated semester broadcast schedule.'})];});});}
 function parseHartt(html){const $=load(html),cards=$('.capsule-interior-pad').filter((i,e)=>$(e).find('h3').length&&$(e).find('iframe').length);if(!cards.length)throw new Error('Hartt broadcast card missing');return cards.toArray().flatMap(card=>{const title=clean($(card).find('h3').first().text()),date=clean($(card).find('h3').first().next('p').text()),stream=publicVideo($(card).find('iframe').attr('src'));if(!stream||excluded(title)||restricted($(card).text()))return [];if(!/\b20\d{2}\b/.test(date))throw new Error('Hartt broadcast year missing');return [event('hartt',title,dateTime(date),{stream_url:stream,watch_kind:'direct',evidence:'Official dated broadcast card embeds this public YouTube player. Campus-local time uses America/New_York, including daylight saving.'})];});}
 function parseIthaca(html,now){const $=load(html),body=$('main .body-text');if(!/list of all that we will have available to stream/i.test(body.text()))throw new Error('Ithaca webcast policy missing');const result=[];const months={Jan:'January',Feb:'February',Mar:'March',Apr:'April',May:'May',Jun:'June',Jul:'July',Aug:'August',Sep:'September',Oct:'October',Nov:'November',Dec:'December'};let month;for(const p of body.find('p').toArray()){const lines=($(p).html()||'').split(/<br\s*\/?\s*>/i).map(clean).filter(Boolean);for(const line of lines){if(months[line]){month=months[line];continue;}const m=line.match(/^(\d{1,2})\s*[–-]\s*(\w+)\s*[–-]\s*(.*?)\s*[–-]\s*(.*?)\s*[–-]\s*(.+)$/);if(!m)continue;if(!month)throw new Error('Ithaca month heading missing');const [,day,week,clock,,title]=m;if(excluded(title))continue;const date=nearbyDate(`${week} ${month} ${day}`,now);result.push(event('ithaca',title,zonedTime(date+'T'+clock24(clock),east),{stream_url:'https://www.ithaca.edu/academics/school-music-theatre-and-dance/live/watch-live',watch_note:'Choose the concert hall player on Ithaca’s Watch Live page.',evidence:'Official webcast-only schedule; year resolved from nearby month/day and verified weekday, never the page footer.'}));}}if(!result.length)throw new Error('Ithaca dated webcast rows missing');return result;}
 function parseFsu(html){const $=load(html);if(!/Content.*only available.*during.*scheduled events/is.test($('body').text()))throw new Error('WFSU scheduled-broadcast policy missing');const rows=$('table tr').filter((i,e)=>$(e).find('td').length===2);if(!rows.length)throw new Error('WFSU stream schedule missing');return rows.toArray().flatMap(row=>{const cells=$(row).find('td'),title=clean(cells.eq(1).text()),date=clean(cells.eq(0).text());if(excluded(title))return [];if(!/\b20\d{2}\b/.test(date))throw new Error('WFSU broadcast year missing');return [event('fsu',title,dateTime(date),{watch_note:'WFSU’s public FSU Music player is available only during scheduled broadcasts.',evidence:'WFSU lists this dated FSU concert under its live-player schedule. Campus-local Eastern time uses DST rules; the page applies EDT generically, even in winter.'})];});}
 function parseCrane(html){const $=load(html),heading=$('h3').filter((i,e)=>/Next Live-Streamed Event/i.test($(e).text())).first();if(!heading.length)throw new Error('Crane next-broadcast section missing');const p=heading.next('p'),text=clean(p.text()),title=clean(p.find('strong').first().text()),a=p.find('a').filter((i,e)=>/Watch the Livestream/i.test($(e).text())).first();if(!a.length||!title||excluded(title)||restricted(text))return [];const url=safeUrl(a.attr('href'));if(!url||new URL(url).hostname!=='www.youtube.com')throw new Error('Crane public-player destination changed');if(!/\b20\d{2}\b/.test(text))throw new Error('Crane year missing');weekday(namedDate(text),text);return [event('crane',title,dateTime(text),{stream_url:url,watch_kind:'channel',watch_note:'Open the scheduled broadcast in Crane’s YouTube livestream playlist.',evidence:'Only the explicitly named Next Live-Streamed Event is admitted; the separate general performance calendar is not evidence of streaming.'})];}
 function parseCsulb(html,policy){const $=load(html);if(!/streaming all our live concerts from (?:the )?Daniel Recital Hall/i.test(clean(policy)))throw new Error('Long Beach hall-specific streaming policy missing');const rows=$('.mix.event');if(!rows.length)throw new Error('Long Beach calendar layout changed');return rows.toArray().flatMap(row=>{const card=$(row),title=clean((card.find('.eventtitle').html()||'').replace(/<br\s*\/?\s*>/gi,' — '));if(clean(card.attr('data-venue'))!=='Daniel Recital Hall'||excluded(title)||restricted(card.find('.description').text()))return [];const date=clean(card.find('.icon.date').text()),time=clean(card.find('.icon.time').text());if(!/\b20\d{2}\b/.test(date)||/\d\s*[-–/]\s*\d/.test(date))return [];const day=namedDate(date);weekday(day,date);return [event('csulb',title,dateTime(date+' '+time,'America/Los_Angeles'),{stream_url:'https://www.youtube.com/@BCCMLiveEvents',watch_kind:'channel',watch_note:'Select this concert on Bob Cole Conservatory’s live-events YouTube channel.',evidence:'Official school policy streams all Daniel Recital Hall concerts; event is in that exact hall. Physical admission charges do not describe online access.'})];});}
 function parseFrost(data,now){if(!Array.isArray(data?.events))throw new Error('Frost Localist feed changed');return data.events.flatMap(({event:e})=>{if(!e?.departments?.some(d=>d.id===31875057946899))throw new Error('Frost department filter failed');if(e.status!=='live'||e.private||e.rejected||excluded(e.title)||restricted((e.stream_info||'')+' '+clean(e.description))||!['hybrid','virtual'].includes(e.experience))return [];const stream=publicVideo(e.stream_url);if(!stream)return [];const url=official(e.localist_url,'https://events.miami.edu');return (e.event_instances||[]).flatMap(({event_instance:i})=>{if(i.all_day||!i.start||!inWindow(i.start,now))return [];const start=zonedTime(i.start.slice(0,19),east);if(Date.parse(start)!==Date.parse(i.start))throw new Error('Frost offset and campus time disagree');return [event('frost',clean(e.title),start,{id:`frost-${e.id}-${i.id}`,event_url:url,stream_url:stream,watch_kind:'direct',evidence_url:url,evidence:'Official Frost event explicitly supplies this public YouTube live URL as its online stream; physical ticket prices are separate.'})];});});}
 async function frost(get,now){const result=[];for(let page=1;page<=3;page++){const data=await get(`https://events.miami.edu/api/2/events?group_id=31875057946899&start=${new Date(+now-2*DAY).toISOString().slice(0,10)}&days=47&pp=100&page=${page}`,true);if(+data?.page?.current!==page||!Number.isInteger(data?.page?.total)||data.page.total>3)throw new Error('Frost pagination changed');result.push(...parseFrost(data,now));if(page>=data.page.total)return result;}throw new Error('Frost pagination exceeded bound');}
 function byuCandidates(html,now){const $=load(html);if(!/Streaming Calendar/i.test($('h1').text()))throw new Error('BYU streaming calendar missing');const cards=$('.PromoCardImageOnTop');if(!cards.length||cards.length>30)throw new Error('BYU streaming cards missing or over bound');return cards.toArray().flatMap(card=>{const c=$(card),title=clean(c.find('h3').text());if(excluded(title))return [];const url=safeUrl(c.find('h3 a').attr('href'));if(!url||!['onstage.byu.edu','music.byu.edu'].includes(new URL(url).hostname))throw new Error('BYU event destination changed');const date=nearbyDate(clean(c.find('.PromoCardImageOnTop-eventDate').text()),now),start=zonedTime(date+'T'+clock24(clean(c.find('.PromoCardImageOnTop-eventTime').text())),'America/Denver');return inWindow(start,now)?[{title,url,start}]:[];});}
 function parseByuIcs(ics,candidate){const blocks=ics.replace(/\r?\n[ \t]/g,'').match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/g);if(blocks?.length!==1)throw new Error('BYU calendar event ambiguous');const block=blocks[0];if(/STATUS:CANCELLED/i.test(block))return null;const stamp=block.match(/^DTSTART;TZID=America\/Denver:(\d{4})(\d\d)(\d\d)T(\d\d)(\d\d)(\d\d)\r?$/m);if(!stamp)throw new Error('BYU calendar time zone missing');const [,y,m,d,h,min,s]=stamp,start=zonedTime(`${y}-${m}-${d}T${h}:${min}:${s}`,'America/Denver');if(start!==candidate.start)throw new Error('BYU streaming calendar and iCal time disagree');const location=block.match(/^LOCATION:(.*)$/m)?.[1]||'',hall=location.match(/\b(Recital|Concert|Choral) Hall/i)?.[1]?.toLowerCase();if(!hall)return null;return event('byu',candidate.title,start,{event_url:candidate.url,stream_url:`https://musicstreaming.byu.edu/${hall}-hall-stream`,evidence_url:candidate.url,watch_note:`BYU’s public ${hall} hall player. Stream availability follows the published streaming calendar.`,evidence:'Listed in BYU’s free streaming calendar, with date/time cross-checked against the official event iCal and hall-specific public player.'});}
 async function byu(get,now){const home=await get('https://musicstreaming.byu.edu/');if(!/streamed performances are free and have no cost/i.test(clean(home)))throw new Error('BYU public-stream policy missing');const candidates=byuCandidates(await get(info.byu.url),now),events=[];for(const c of candidates){const $=load(await get(c.url)),a=$('a[href]').filter((i,e)=>/Add to Calendar/i.test($(e).text())).first();if(!a.length)throw new Error('BYU iCal link missing');const url=official(a.attr('href'),c.url);if(new URL(url).pathname!=='/_event.ics')throw new Error('BYU iCal path changed');const event=parseByuIcs(await get(url),c);if(event)events.push(event);}return events;}
 const parsers={parseBu,parseHartt,parseIthaca,parseFsu,parseCrane,parseCsulb,parseFrost,byuCandidates,parseByuIcs};
 const raw={bu:async get=>parseBu(await get(info.bu.url)),hartt:async get=>parseHartt(await get(info.hartt.url)),ithaca:async(get,now)=>parseIthaca(await get(info.ithaca.url),now),fsu:async get=>parseFsu(await get(info.fsu.url)),crane:async get=>parseCrane(await get(info.crane.url)),csulb:async get=>parseCsulb(await get(info.csulb.url),await get('https://web.csulb.edu/colleges/cota/music/')),frost,byu};
 return {parsers,adapters:Object.fromEntries(Object.entries(raw).map(([id,adapter])=>[id,async(get,now)=>(await adapter(get,now)).filter(e=>inWindow(e.start,now))]))};
}
